sudo: required
services:
  - docker

before_install:
  - docker build -t bdexley5/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bdexley5/react-test npm test

after_success:
  - docker build -t bdexley5/multi-client ./client
  - docker build -t bdexley5/multi-nginx ./nginx
  - docker build -t bdexley5/multi-server ./server
  - docker build -t bdexley5/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push bdexley5/multi-client
  - docker push bdexley5/multi-nginx
  - docker push bdexley5/multi-server
  - docker push bdexley5/multi-worker
  
deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-309155248416
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

