sudo: required
services:
  - docker

before_install:
  - docker build -t bdexley5/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bdexley5/react-test npm test

after_success:
  - docker build -t bdexley5/multi-client ./client
  - docker build -t bdexley5/multi-nginx ./nginx
  - docker build -t bdexley5/multi-server ./server
  - docker build -t bdexley5/multi-worker ./worker
  # Take those images and push them to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bdexley5/multi-client
  - docker push bdexley5/multi-nginx
  - docker push bdexley5/multi-server
  - docker push bdexley5/multi-worker
  
  